In [1]:
import numpy as np
import pandas as pd 
import pickle

In [2]:
dataset = pd.read_csv("personality_dataset.csv")

In [3]:
print(dataset.isnull().sum())

Time_spent_Alone             63
Stage_fear                   73
Social_event_attendance      62
Going_outside                66
Drained_after_socializing    52
Friends_circle_size          77
Post_frequency               65
Personality                   0
dtype: int64


In [4]:
from sklearn.preprocessing import LabelEncoder

le1 = LabelEncoder()
le2 = LabelEncoder()

dataset.iloc[:, 1] = le1.fit_transform(dataset.iloc[:, 1])
dataset.iloc[:, 4] = le2.fit_transform(dataset.iloc[:, 4])

# After fitting

pickle.dump(le1, open("le1.pkl", "wb"))
pickle.dump(le2, open("le2.pkl", "wb"))



In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(dataset.iloc[:, 0:7])
dataset.iloc[:, 0:7] = imputer.transform(dataset.iloc[:, 0:7])

In [6]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [7]:
from sklearn.preprocessing import LabelEncoder
le3 = LabelEncoder()
y = le3.fit_transform(y)
pickle.dump(le3, open("le3.pkl", "wb"))

In [8]:
print(y)

[0 1 1 ... 1 1 0]


In [9]:
print(X)

[[4.0 0.0 4.0 ... 0.0 13.0 5.0]
 [9.0 1.0 0.0 ... 1.0 0.0 3.0]
 [9.0 1.0 1.0 ... 1.0 5.0 2.0]
 ...
 [4.0 1.0 1.0 ... 1.0 4.0 0.0]
 [11.0 1.0 1.0 ... 1.0 2.0 0.0]
 [3.0 0.0 6.0 ... 0.0 6.0 9.0]]


In [10]:
print(y)

[0 1 1 ... 1 1 0]


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [12]:
print(X_train)

[[8.0 1.0 1.0 ... 1.0 1.0 1.0]
 [7.0 1.0 2.0 ... 1.0 1.0 2.0]
 [9.0 1.0 1.0 ... 1.0 4.0 1.0]
 ...
 [6.0 1.0 1.0 ... 2.0 5.0 2.0]
 [10.0 1.0 3.0 ... 1.0 1.0 2.0]
 [11.0 1.0 1.0 ... 1.0 2.0 2.0]]


In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
pickle.dump(sc, open("scaler.pkl", "wb"))

In [14]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
pickle.dump(classifier,open("model.pkl","wb"))

In [15]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [1 1]
 [0 0]
 ...
 [1 1]
 [0 0]
 [0 0]]


In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)


[[325  21]
 [ 29 350]]


In [17]:
accuracy_score(y_test, y_pred)

0.9310344827586207